language: node_js
node_js:
  - 0.6
  - 0.7
  - 0.8
  - 0.9
  - 0.10

services:
  - couchdb

before_script:
  - curl -X PUT http://127.0.0.1:5984/foobar
  - curl -X PUT http://127.0.0.1:5984/_config/admins/zoddy --data '"zoddy"'
